version: 1

formatters:
  default:
    format: '%(levelname)s: %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    formatter: default

loggers:
  main:
    level: INFO
    handlers: [console]
    propagate: no

root:
  level: DEBUG
  handlers: [console]
