version: 1

formatters:
  default:
    format: '%(levelname)s: %(message)s'

  colored:
    (): 'colorlog.ColoredFormatter'
    format: '%(log_color)s%(levelname)s:%(reset)s%(message_log_color)s%(message)s'
    log_colors:
      TRACE: cyan
      REVIEW: green
      DEBUG: purple
      INFO: green
      WARNING: yellow
      ERROR: red
      CRITICAL: red,bg_white
    secondary_log_colors:
      message:
        TRACE: purple
        REVIEW: cyan
        WARNING: yellow
        ERROR: red
        CRITICAL: red

handlers:
  console:
    class: logging.StreamHandler
    formatter: colored

loggers:
  main:
    level: INFO
    handlers: [console]
    propagate: no

root:
  level: DEBUG
  handlers: [console]
