# This is the main config file for 7m_video_sorter

# The directory it will search for the videos
input_dir: "sample/Input Folder/"

# The direcotry it will copy the videos
output_dir: "sample/Output Folder/"

# Files to ignore in input folder
ignore:
  - ".stversions"
